# Generated by Django 3.1.1 on 2021-06-06 14:08

import autoslug.fields
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='location name')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country of Origin')),
            ],
        ),
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Dinosaur')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Cheese Address')),
                ('pronunciation', models.CharField(max_length=120, verbose_name='How to Pronounce the Name')),
                ('length', models.IntegerField(verbose_name='Length of Dinosaur')),
                ('image', models.ImageField(upload_to='upload/images/')),
                ('scale', models.ImageField(upload_to='upload/images/')),
                ('diet', models.CharField(choices=[('unknown', 'UnKnown'), ('herbivorous', 'Herbivorous'), ('omnivorous', 'Omnivorous'), ('carnivorous', 'Carnivorous')], default='unknown', max_length=25, verbose_name='Diet of the Dinosaur')),
                ('period', models.CharField(choices=[('unknown', 'UnKnown'), ('Late Triassic', 'Lt'), ('Early Jurassic', 'Ej'), ('Mid Jurassic', 'Mj'), ('Late Jurassic', 'Lj'), ('Early Cretaceous', 'Ec'), ('Late Cretaceous', 'Lc')], default='unknown', max_length=25, verbose_name='Period of time when dinosaur lived')),
                ('typeofdino', models.CharField(choices=[('unknown', 'UnKnown'), ('Armoured dinosaurs', 'Ad'), ('Ceratopsian', 'C'), ('Euornithopod', 'E'), ('Sauropod', 'S'), ('Large theropod', 'Lt'), ('Small theropod', 'St')], default='unknown', max_length=25, verbose_name='Type of Dinosaur')),
                ('species', models.CharField(max_length=25, verbose_name='Species of Dinosaur')),
                ('locations', models.ManyToManyField(to='dinos.Location')),
            ],
        ),
    ]
