# Generated by Django 3.1.1 on 2021-06-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinos', '0002_auto_20210606_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='country',
            new_name='name',
        ),
    ]
