# Generated by Django 3.1.1 on 2021-06-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinos', '0003_auto_20210606_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinosaur',
            name='image',
        ),
        migrations.RemoveField(
            model_name='dinosaur',
            name='scale',
        ),
    ]
