# Generated by Django 3.1.1 on 2021-06-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinos', '0004_auto_20210611_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinosaur',
            name='locations',
            field=models.ManyToManyField(related_name='dinosaurs', to='dinos.Location'),
        ),
    ]
